http:
  routers:
    nginx:
      rule: Host(`web.localhost`)
      service: service-nginx
      middlewares:
        - exceptions
      entrypoints:
        - web

    error-pages:
      rule: HostRegexp(`{host:.+}`)
      priority: 1
      service: service-error-pages
      entryPoints:
        - web

  services:
    service-nginx:
      loadbalancer:
        servers:
          - url: http://<your-ip>:80

    service-error-pages:
      loadbalancer:
        servers:
          - url: http://<your-ip>:8090

  middlewares:
    # Handle service exceptions.
    exceptions:
      errors:
        status:
          - "400-599"
      service: service-error-pages
      query: "/{status}.html"
